export const mock_data = [
  { id: 1, name: 'Taken', mainChar: 'Winnie Curwen', rating: 2.0 },
  { id: 2, name: 'Black Hole, The', mainChar: 'Kikelia Kupka', rating: 9.9 },
  {
    id: 3,
    name: 'Play Time (a.k.a. Playtime)',
    mainChar: 'Eugenio Presnail',
    rating: 9.8,
  },
  {
    id: 4,
    name: 'All the Mornings of the World (Tous les matins du monde)',
    mainChar: 'Mureil Busher',
    rating: 2.7,
  },
  {
    id: 5,
    name: 'Somewhere Between',
    mainChar: 'Elicia Tollmache',
    rating: 4.7,
  },
  {
    id: 6,
    name: 'Remo Williams: The Adventure Begins',
    mainChar: 'Phylys Rehor',
    rating: 6.5,
  },
  { id: 7, name: 'Jade', mainChar: 'Linea Dalzell', rating: 7.9 },
  { id: 8, name: 'Love Affair', mainChar: 'Sigismundo Ivakhno', rating: 5.9 },
  { id: 9, name: 'Skyscraper Souls', mainChar: 'Jefferey Rugge', rating: 8.0 },
  {
    id: 10,
    name: 'A Justified Life: Sam Peckinpah and the High Country',
    mainChar: 'Ally Balog',
    rating: 2.0,
  },
  { id: 11, name: 'Our Nixon', mainChar: 'Shanta Danton', rating: 8.9 },
  {
    id: 12,
    name: 'Jamie and Jessie Are Not Together',
    mainChar: 'Gianina Sedgeman',
    rating: 3.1,
  },
  { id: 13, name: 'Samaritan, The', mainChar: 'Ash Larvin', rating: 4.8 },
  {
    id: 14,
    name: 'Dark Blue World (Tmavomodrý svet)',
    mainChar: 'Abey Rawes',
    rating: 6.0,
  },
  { id: 15, name: 'Onion Field, The', mainChar: 'Alon Moseby', rating: 7.1 },
  {
    id: 16,
    name: 'American Ninja 4: The Annihilation',
    mainChar: 'Omar Happert',
    rating: 5.5,
  },
  { id: 17, name: 'Law and Order', mainChar: 'Alma Cornner', rating: 9.5 },
  {
    id: 18,
    name: 'Between Your Legs (Entre las piernas)',
    mainChar: 'Christan Rosso',
    rating: 9.8,
  },
  { id: 19, name: 'MacArthur', mainChar: 'Clifford Forber', rating: 7.2 },
  { id: 20, name: 'Waiting to Exhale', mainChar: 'Morey Cantor', rating: 2.9 },
  {
    id: 21,
    name: 'The Inhabited Island',
    mainChar: 'Lauritz Ruilton',
    rating: 1.5,
  },
  { id: 22, name: 'Damage (Fatale)', mainChar: 'Robbyn Van Oort', rating: 7.9 },
  {
    id: 23,
    name: 'Guest House Paradiso',
    mainChar: 'Cherise Dearle',
    rating: 7.6,
  },
  { id: 24, name: 'Out of the Fog', mainChar: 'Garrott Dahlborg', rating: 5.9 },
  { id: 25, name: 'Fading Gigolo', mainChar: 'Aurlie Quilliam', rating: 7.0 },
  { id: 26, name: 'Angie', mainChar: 'Jolyn Alker', rating: 1.4 },
  {
    id: 27,
    name: 'Unknown Known, The',
    mainChar: 'Lynett McWilliam',
    rating: 5.1,
  },
  {
    id: 28,
    name: "Outfoxed: Rupert Murdoch's War on Journalism",
    mainChar: 'Gwendolen Eatttok',
    rating: 1.5,
  },
  { id: 29, name: 'Born to Dance', mainChar: 'Wendell Dubbin', rating: 8.2 },
  {
    id: 30,
    name: 'My Piece of the Pie (Ma part du gâteau)',
    mainChar: 'Gabriell Krysztowczyk',
    rating: 5.2,
  },
  { id: 31, name: 'In-Laws, The', mainChar: 'Kennedy Britee', rating: 8.7 },
  { id: 32, name: 'Cry Freedom', mainChar: 'Euell Partridge', rating: 7.3 },
  { id: 33, name: 'Tinpis Run', mainChar: 'Halette Dymocke', rating: 3.6 },
  { id: 34, name: 'Honeymooners, The', mainChar: 'Terrel Daenen', rating: 5.3 },
  { id: 35, name: 'Tango Kabaree', mainChar: 'Trever Calderwood', rating: 5.0 },
  {
    id: 36,
    name: 'Story of Vernon and Irene Castle, The',
    mainChar: 'Gussy Lidbetter',
    rating: 4.3,
  },
  { id: 37, name: 'Michael', mainChar: 'Madeleine Trevance', rating: 1.3 },
  {
    id: 38,
    name: 'Den tatuerade änkan (Tattooed Widow, The) ',
    mainChar: 'Kitty McCooke',
    rating: 3.6,
  },
  { id: 39, name: 'Krrish 3', mainChar: 'Carie Fipp', rating: 6.6 },
  {
    id: 40,
    name: "Life of Another, The (La vie d'une autre)",
    mainChar: 'Todd Teaz',
    rating: 5.1,
  },
  { id: 41, name: 'Film Geek', mainChar: 'Vern Prescote', rating: 8.0 },
  {
    id: 42,
    name: 'Despicable Me 2',
    mainChar: 'Mirna Bartoszewski',
    rating: 5.1,
  },
  {
    id: 43,
    name: 'Tucker: The Man and His Dream',
    mainChar: 'Shurwood MacIlraith',
    rating: 7.9,
  },
  { id: 44, name: 'Killers, The', mainChar: 'Emmott Jurkiewicz', rating: 7.2 },
  { id: 45, name: 'Dark Blue', mainChar: 'Angelle Gooms', rating: 5.6 },
  {
    id: 46,
    name: 'Scott Pilgrim vs. the World',
    mainChar: 'Karlan Rogans',
    rating: 2.2,
  },
  { id: 47, name: 'Stargate: Continuum', mainChar: 'Doe Roget', rating: 8.8 },
  {
    id: 48,
    name: 'Fifty Dead Men Walking',
    mainChar: 'Maryjane Konertz',
    rating: 7.1,
  },
  { id: 49, name: 'Acacias, Las', mainChar: 'Gradeigh Catt', rating: 2.3 },
  {
    id: 50,
    name: 'Lupin III: Sweet Lost Night (Rupan Sansei: Sweet Lost Night)',
    mainChar: 'Tedda Ziehm',
    rating: 8.6,
  },
  {
    id: 51,
    name: 'Mrs. Parker and the Vicious Circle',
    mainChar: 'Cyrillus Gant',
    rating: 3.8,
  },
  { id: 52, name: 'D.O.A.', mainChar: 'Charmion Gaddas', rating: 5.4 },
  {
    id: 53,
    name: 'Round Up, The (La Rafle)',
    mainChar: 'Marj Bevans',
    rating: 7.4,
  },
  { id: 54, name: 'Maltese Falcon, The', mainChar: 'Aggi Cowins', rating: 2.3 },
  {
    id: 55,
    name: 'Toy, The (Le jouet)',
    mainChar: 'Laurella Arrundale',
    rating: 8.8,
  },
  {
    id: 56,
    name: 'Divorce Iranian Style',
    mainChar: 'Elmer Carslake',
    rating: 3.8,
  },
  { id: 57, name: 'Street Fighter', mainChar: 'Gardner Kilius', rating: 6.8 },
  { id: 58, name: 'Black Dawn', mainChar: 'Dorine McCarter', rating: 5.6 },
  { id: 59, name: 'Big Lift, The', mainChar: 'Brody Robelet', rating: 4.0 },
  {
    id: 60,
    name: 'Castle of Sand, The (Suna no utsuwa)',
    mainChar: 'Nettie Sloegrave',
    rating: 1.4,
  },
  {
    id: 61,
    name: 'Hippie Revolution, The',
    mainChar: 'Shannah Seeking',
    rating: 4.1,
  },
  { id: 62, name: 'The D.I.', mainChar: 'Ab Nyland', rating: 7.5 },
  {
    id: 63,
    name: 'Shake Hands with the Devil',
    mainChar: 'Ryley Rumble',
    rating: 1.9,
  },
  { id: 64, name: '360', mainChar: 'Glynnis Chyuerton', rating: 4.6 },
  {
    id: 65,
    name: 'Dancing Hawk, The (Tanczacy jastrzab)',
    mainChar: 'Dominique Kenryd',
    rating: 2.2,
  },
  { id: 66, name: 'StreetDance 3D', mainChar: 'Brennen Geffe', rating: 9.6 },
  {
    id: 67,
    name: '27 Missing Kisses',
    mainChar: 'Martguerita Hanley',
    rating: 2.0,
  },
  {
    id: 68,
    name: 'Mermaid, The (Rusalka)',
    mainChar: 'Ranique Winney',
    rating: 8.5,
  },
  { id: 69, name: 'Beethoven', mainChar: 'Free Ghion', rating: 3.6 },
  {
    id: 70,
    name: 'Hurricane Streets',
    mainChar: 'Whittaker Arbuckel',
    rating: 8.8,
  },
  {
    id: 71,
    name: 'Al Franken: God Spoke',
    mainChar: 'Ottilie Folds',
    rating: 9.7,
  },
  {
    id: 72,
    name: 'Art of the Steal, The',
    mainChar: 'Sauncho Ivens',
    rating: 7.5,
  },
  {
    id: 73,
    name: 'Unaccompanied Minors',
    mainChar: 'Daniella De Lascy',
    rating: 3.4,
  },
  { id: 74, name: 'Kolberg', mainChar: 'Forest Paladino', rating: 9.5 },
  { id: 75, name: 'Tender Mercies', mainChar: 'Anallise Leyson', rating: 3.4 },
  {
    id: 76,
    name: 'Dolly Sisters, The',
    mainChar: 'Tomi Titchmarsh',
    rating: 4.7,
  },
  {
    id: 77,
    name: 'Bunny Lake Is Missing',
    mainChar: 'Shelba Klimke',
    rating: 3.0,
  },
  {
    id: 78,
    name: 'House of Sand and Fog',
    mainChar: 'Emily Worg',
    rating: 2.8,
  },
  {
    id: 79,
    name: 'Breaking and Entering',
    mainChar: 'Eugenia Sarsfield',
    rating: 9.3,
  },
  { id: 80, name: 'Never Again', mainChar: 'Thomasa Heam', rating: 8.3 },
  {
    id: 81,
    name: 'House on Haunted Hill',
    mainChar: 'Biddie Midlane',
    rating: 3.6,
  },
  {
    id: 82,
    name: 'Stranger in Town, A',
    mainChar: 'Rozanne Adamik',
    rating: 9.6,
  },
  {
    id: 83,
    name: "Mr. Toad's Wild Ride (a.k.a. The Wind in the Willows)",
    mainChar: 'Tannie Antley',
    rating: 4.5,
  },
  {
    id: 84,
    name: 'Mission: Impossible II',
    mainChar: 'Bank Broxis',
    rating: 5.3,
  },
  {
    id: 85,
    name: 'Craig Ferguson: Does This Need to Be Said?',
    mainChar: 'Haley Braxton',
    rating: 2.8,
  },
  {
    id: 86,
    name: 'Balkan Spy (Balkanski spijun)',
    mainChar: 'Sandie Simukov',
    rating: 5.4,
  },
  { id: 87, name: 'Entrapment', mainChar: 'Anitra Loverock', rating: 1.8 },
  {
    id: 88,
    name: 'Raw Deal: A Question of Consent',
    mainChar: 'Rurik Binnion',
    rating: 9.1,
  },
  { id: 89, name: 'Salvage', mainChar: 'Laverne Smullin', rating: 2.4 },
  {
    id: 90,
    name: 'Time in the Minors',
    mainChar: 'Christiane Oleshunin',
    rating: 4.8,
  },
  {
    id: 91,
    name: "Big Momma's House 2",
    mainChar: 'Phylys Shinner',
    rating: 9.8,
  },
  { id: 92, name: 'T-Men', mainChar: 'Darryl Ariss', rating: 3.3 },
  {
    id: 93,
    name: 'White God (Fehér isten)',
    mainChar: 'Sheena Minci',
    rating: 7.4,
  },
  {
    id: 94,
    name: 'Idle Mist (Vana Espuma)',
    mainChar: 'Timmi Duffell',
    rating: 5.2,
  },
  {
    id: 95,
    name: 'Man Who Knew Too Much, The',
    mainChar: 'Louie Dury',
    rating: 1.2,
  },
  {
    id: 96,
    name: 'Run of the Country, The',
    mainChar: 'Sephira Woollons',
    rating: 9.2,
  },
  { id: 97, name: 'Promotion, The', mainChar: 'Gail Tills', rating: 6.0 },
  {
    id: 98,
    name: 'Still Life (Sanxia haoren)',
    mainChar: 'Ambrosi Godar',
    rating: 2.2,
  },
  { id: 99, name: 'Bob Funk', mainChar: 'Vinnie McGaugan', rating: 9.7 },
  {
    id: 100,
    name: 'Sometimes a Great Notion',
    mainChar: 'Caty Wingate',
    rating: 8.0,
  },
];
